## Create Interactive Plots with Plotly
In this notebook, we will learn how to use `plotly` library to build interactive plots.

Plotly library: Plotly's Python graphing library makes interactive, publication-quality graphs online. Examples of how to make line plots, scatter plots, area charts, bar charts, error bars, box plots, histograms, heatmaps, subplots, multiple-axes, polar charts, and bubble charts.

In [2]:
# Run this if plotly is not installed yet
#!pip install plotly==5.24.1
# !pip install plotly.express --quiet
# !pip show plotly

In [3]:
### Importing libraries
import numpy as np
import pandas as pd

# plotly libraries
from plotly.offline import init_notebook_mode, iplot, plot
import plotly as py
init_notebook_mode(connected=True)
import plotly.graph_objs as go
import plotly.express as px

# matplotlib
import matplotlib.pyplot as plt
import warnings; warnings.filterwarnings("ignore")

In [4]:
### If running plotly in Google colab, you will need to run this custom initialization function
### in each offline plotting cell to embed HTML content in Jupyter notebook
def configure_plotly_browser_state():
  import IPython
  display(IPython.core.display.HTML('''
        <script src="/static/components/requirejs/require.js"></script>
        <script>
          requirejs.config({
            paths: {
              base: '/static/base',
              plotly: 'https://cdn.plot.ly/plotly-latest.min.js?noext',
            },
          });
        </script>
        '''))

## University World rank dataset
University ranking dataset based on measurements captured by Times Higher Education World University Ranking.

Dataset fields:
- `world_rank` -  world rank for the university
- `university_name` -  name of university
- `country` - country of each university
- `teaching` - university score for teaching (the learning environment)
- `international` - university score international outlook (staff, students, research)
- `research` - university score for research (volume, income and reputation)
- `citations` - university score for citations (research influence)
- `income` - university score for industry income (knowledge transfer)
- `total_score` - total score for university, used to determine rank
- `num_students` - number of students at the university
- `student_staff_ratio` - Number of students divided by number of staff
- `international_students` - Percentage of students who are international
- `female_male_ratio` - Female student to Male student ratio
- `year` - year of the ranking (2011 to 2016 included)

In [5]:
# University World rank dataset
dataset = "https://raw.githubusercontent.com/csbfx/advpy122-data/master/timesData.csv"
uni = pd.read_csv(dataset)

In [6]:
# uni.info()
# uni.head()

In [7]:
### Notice the "world_rank" column and the extra string.
## These strings in the column that need to be remove
uni[uni.world_rank.str.contains('=')]

,world_rank,university_name,country,teaching,international,research,citations,income,total_score,num_students,student_staff_ratio,international_students,female_male_ratio,year
1841,=39,"University of California, San Diego",United States of America,56.9,42.9,69.8,98.7,56.7,72.2,"27,233",6.5,11%,48 : 52,2016
1842,=39,"University of California, Santa Barbara",United States of America,52.6,61.5,66.0,99.2,90.4,72.2,"22,020",27.3,11%,52 : 48,2016
1846,=44,"University of California, Davis",United States of America,60.1,58.4,72.7,84.3,57.3,71.0,"35,364",13.9,13%,54 : 46,2016
1847,=44,University of Hong Kong,Hong Kong,64.6,99.5,72.8,70.1,53.7,71.0,"19,835",17.6,38%,53 : 47,2016
1849,=47,Tsinghua University,China,73.3,39.5,83.0,58.8,100.0,70.0,"39,763",13.7,10%,32 : 68,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1993,=190,Boston College,United States of America,34.1,60.0,29.3,83.3,46.8,49.6,"13,216",17.4,19%,54 : 46,2016
1995,=193,University of Luxembourg,Luxembourg,25.0,99.8,26.7,84.8,38.1,49.4,"5,144",15.9,52%,50 : 50,2016
1996,=193,Texas A&M University,United States of America,49.4,47.8,52.4,47.1,46.4,49.4,"50,657",21.4,9%,47 : 53,2016
1998,=196,Newcastle University,United Kingdom,30.9,84.3,27.5,81.5,34.7,49.2,"20,174",15.2,29%,50 : 50,2016
1999,=196,"St George’s, University of London",United Kingdom,25.6,69.5,18.1,100.0,37.7,49.2,"2,958",13.4,17%,61 : 39,2016

In [8]:
### Clean the world_rank data since some values starts with an = sign
## Find the row where there is no "=" string
duni = uni[uni.world_rank.str.contains('=')==False]

## Find the row where the value is True, ie contain "=" string. Replace the string
dunib = uni[uni.world_rank.str.contains('=')==<?>]
dunib.world_rank = uni.world_rank.str.replace(<org>,<new>)

## Convert column to numeric with any value that can't be converted replace with NaN via error='coerce'
duni.world_rank = pd.to_numeric(<df.colname>, errors='coerce')
dunib.world_rank =


## Concatenate along the row without sorting label alphabetically
uni = pd.concat([<list of df to concatenate>], sort=<True,False>)
# uni = uni.sort_index(ascending=True)

In [9]:
# uni.info()

### RBG Colors
You can provide rbg colors for most plots. An easy way is to select a color using Google's color picker (Google "Color Picker") or you can randomly generate a rbg color below. I also like [Color Brewer](https://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3) for selecting colors that are color blind friendly.

In [10]:
# Random RBG color generator
import numpy as np
color = list(np.random.choice(range(256), size=3))
print(color)

[np.int64(254), np.int64(165), np.int64(141)]

## Line Chart
Let's plot `citation` and `teaching` vs `world_rank` of Top 100 Universities

We will use plotly `Scatter` object. Ref: [plotly.graph_objects.Scatter](https://plotly.com/python-api-reference/generated/plotly.graph_objects.Scatter.html). In addition, we will create traces which are graph objects.

A trace object will contain the actual data (such as the x and y coordinates),  along with all the associated visual attributes like color, size, line style, and marker shape. Using traces, we can interact with the plot by clicking on a legend item to hide or show that trace.

In [11]:
### Run configure_plotly_browser_state() if you are in Google colab
configure_plotly_browser_state()

### Get the top 100 universities
df = uni.iloc[:100,:]

### import graph objects as "go"
import plotly.graph_objs as go

# Creating trace1
trace1 = go.Scatter(
                    x = df.world_rank,
                    y = df.citations,
                    mode = <plot type attribute>,
                    name = <colname>,
                    marker = dict(color = 'rgba(172, 135, 11, 0.8)'),
                    text= <hover shows?>)

# Creating trace2 (add additional marker mode)
trace2 = go.Scatter(
                    x = df.world_rank,
                    y = df.teaching,
                    mode = "lines+markers",
                    name = "teaching",
                    marker = dict(color = 'rgba(127, 207, 159, 0.8)'),
                    text= df.university_name)

data = [trace1, trace2]

layout = dict(title = 'Citation and Teaching vs World Rank of Top 100 Universities',
              xaxis= dict(title= 'World Rank', ticklen= 5, zeroline= False)
             )

fig = dict(data = data, layout = layout)
iplot(fig)

### Plotly express, `px`
Plotly express, `px`, is a higher-level API that allows us to quickly create interactive plots. It requires minimal code compare to Plotly Graph Objects (go), which is more verbose but enables us to have more customization.

In [12]:
# Plotly express way
configure_plotly_browser_state()

## Static plot
line_plot = px.line(df,
                    x="world_rank",
                    y="citations",
                    hover_data="university_name",
                    title="Enter your titles in the plotting function itself")

trace2 = go.Scatter(
                    x = <df.colname>,
                    y = <df.colname2>,
                    mode = "lines+markers",
                    name = <colname>,
                    marker = dict(color = 'rgba(127, 207, 159, 0.8)'),
                    text= df.university_name)

### Add the trace to line_plot

In [13]:
### Creating a long-form table of teaching and citation for top 100
df = uni.iloc[:100,:]
for_color_test = df.melt(id_vars=[col for col in df.columns if col not in ["teaching", "citations"]],
                         var_name="Score Category",
                         value_name="score")
for_color_test

### Plotly express to create interactive plot
configure_plotly_browser_state()
line_plot = px.line(for_color_test,
                    x="world_rank",
                    y="score",
                    hover_data="university_name",
                    color="Score Category",
                    title="Melt is so useful sometimes",
                    line_dash = "Score Category")

line_plot.show()

### Question 14.1 Create a line plot
Create a plot for the Top 10 Universities showing the citation, research and teaching measurements (score). Allow hover to show university's names.

In [24]:
### Your code

# Scatter plot with plotly `go.Scatter()`
Create a scatter plot for `citation` vs `world rank` of top 100 universities for 2012, 2014 and 2016 using plotly go object.

In [15]:
# Run configure_plotly_browser_state() if you are in Google colab
configure_plotly_browser_state()

df2012 = uni[uni.year == 2012].iloc[:100,:]
df2014 = uni[uni.year == 2014].iloc[:100,:]
df2016 = uni[uni.year == 2016].iloc[:100,:]

## Create trace1 (2012)
trace1 =go.Scatter(
                    x = df2012.world_rank,
                    y = df2012.citations,
                    mode = <type of plot attribute>,
                    name = <trace name>,
                    marker = dict(color = 'rgba(31, 237, 108, 0.8)'),
                    text= <hover over>,
                    )

## Create trace2 (2014)
trace2 =go.Scatter(
                    x = df2014.world_rank,
                    y = df2014.citations,
                    mode = "markers",
                    name = "2014",
                    marker = dict(color = 'rgba(245, 73, 197, 0.8)'),
                    text= df2014.university_name)

## Create trace3 (2016)
trace3 =go.Scatter(
                    x = df2016.world_rank,
                    y = df2016.citations,
                    mode = "markers",
                    name = "2016",
                    marker = dict(color = 'rgba(94, 29, 211, 0.8)'),
                    text= df2016.university_name)

### Combine all three traces
data = [trace1, trace2, trace3]

### Set-up dictionary for plot
layout = dict(title = 'Citation vs world rank of top 100 universities for 2012, 2014 and 2016',
              xaxis= dict(title= 'World Rank', ticklen=10, zeroline= False),
              yaxis= dict(title= 'Citation', ticklen= 5, zeroline= False)
             )

### Fig object and plot
fig = dict(data = data, layout = layout)
iplot(fig)

In [16]:
## Same plot but with plotly express
configure_plotly_browser_state()

px.scatter(uni,
           x="world_rank",
           y="citations",
           color="year",
           title="Citation vs world rank of top 100 universities for 2012, 2014 and 2016"
           )

## Bar Charts using `go.Bar()`
Let's plot `citations` and `teaching` of top 10 universities in 2016

In [17]:
# Run configure_plotly_browser_state() if you are in Google colab
configure_plotly_browser_state()

df2016 = uni[uni.year == 2016].iloc[:10,:]


## Create trace1 (2016 citations)
trace1 = go.Bar(
                x = df2016.university_name,
                y = df2016.citations,
                name = "citations",
                marker = dict(color = 'rgba(123, 153, 23, 0.5)',
                             line=dict(color='rgb(0,0,0)', width=1.5)),
                text = df2016.country
                )

## Create trace2 (2016 teaching)
trace2 = go.Bar(
                x = df2016.university_name,
                y = df2016.teaching,
                name = "teaching",
                marker = dict(color = 'rgba(94, 29, 211, 0.5)',
                              line=dict(color='rgb(0,0,0)',width=1.5)),
                text = df2016.country
                )

### Combine traces
data = [trace1, trace2]

### Setting up layout and assign to figure object
layout = go.Layout(title = 'Citation and teaching for top 10 universities in 2016',
                   barmode = "group",
                   margin=dict(r=200, l=110, b=150, t=60)
                   )

fig = go.Figure(data = data, layout = layout)
iplot(fig)

## Stack bar plots using `'type': 'bar'`

In [19]:
### Run configure_plotly_browser_state() if you are in Google colab
configure_plotly_browser_state()

### Stack plots
x = df2016.university_name

trace1 = {
  'x': x,
  'y': df2016.citations,
  'name': 'citation',
  'type': 'bar'
};

trace2 = {
  'x': x,
  'y': df2016.teaching,
  'name': 'teaching',
  'type': 'bar'
};

### Set up traces
data = [trace1, trace2];

### Change to Stacked plot using 'barmode': 'relative'
layout = {
  'barmode': <'group', 'relative'>,
  'title': 'citations and teaching of top 10 universities in 2016',
  'margin': dict(r=200, l=110, b=180, t=70) # margins useful when you need extra space for things like axis labels, legends, or titles
};

fig = go.Figure(data = data, layout = layout)
iplot(fig)

## Question 14.2: Plot bar plot and stacked bar plot
Create two plots; first is a bar plot showing the top 50 universities measurements for citation, research and teaching.

Convert that plot into a stacked plot

In [ ]:
### Your code
## Bar plot of citation, research and teaching for top 50 universities

In [ ]:
### Your code
## Stacked plot of citation, research and teaching for top 50 universities

## Pie Chart
Let's make a pie chart for `Students rate` of top 5 universities in 2016.

In [20]:
df2016 = uni[uni.year == 2016].iloc[:5,:]
df2016

,world_rank,university_name,country,teaching,international,research,citations,income,total_score,num_students,student_staff_ratio,international_students,female_male_ratio,year
1803,1,California Institute of Technology,United States of America,95.6,64.0,97.6,99.8,97.8,95.2,"2,243",6.9,27%,33 : 67,2016
1804,2,University of Oxford,United Kingdom,86.5,94.4,98.9,98.8,73.1,94.2,"19,919",11.6,34%,46 : 54,2016
1805,3,Stanford University,United States of America,92.5,76.3,96.2,99.9,63.3,93.9,"15,596",7.8,22%,42 : 58,2016
1806,4,University of Cambridge,United Kingdom,88.2,91.5,96.7,97.0,55.0,92.8,"18,812",11.8,34%,46 : 54,2016
1807,5,Massachusetts Institute of Technology,United States of America,89.4,84.0,88.6,99.7,95.4,92.0,"11,074",9.0,33%,37 : 63,2016

In [21]:
# Run configure_plotly_browser_state() if you are in Google colab
configure_plotly_browser_state()

df2016 = uni[uni.year == 2016].iloc[:5,:]
pie1 = df2016.num_students
pie1_list = [float(each.replace(',', '')) for each in df2016.num_students]  # str(2,4) => str(2.4) = > float(2.4) = 2.4
labels = df2016.university_name
# figure
fig = {
  "data": [
    {
      "values": pie1_list,
      "labels": labels,
      "domain": {"x": [0, .5]},
      "name": "Student info",
      "text": pie1_list,
       "hovertemplate":"%{label}: <br>Percent: %{percent} </br> # of Students: %{text}",
      "hole": .3, # adding a hole in the middle
      "type": "pie"
    },],
  "layout": {
        "title":"Number of students from the top 5 universities",
        "annotations": [
            { "font": { "size": 12},
              "showarrow": False,
              "text": " ",
                "x": 0.5,
                "y": 0.8
            },
        ]
    }
}
iplot(fig)

## Bubble plots
Let's create a bubble plot for the `University world rank` (first 20) vs `teaching score` with `number of students`(size) and `international score`(color) in 2016

In [22]:
# Run configure_plotly_browser_state() if you are in Google colab
configure_plotly_browser_state()

df2016 = uni[uni.year == 2016].iloc[:20,:]
num_students_size  = [float(each.replace(',', '.')) for each in df2016.num_students]
international_color = [float(each) for each in df2016.international]

data = [
   {
       'y': df2016.teaching,
       'x': df2016.world_rank,
       'mode': 'markers',
       'marker': {
            'color': international_color,
            'size': num_students_size,
            'showscale': True
       },
       "text" :  df2016.university_name # additional info that you see when hovering over
    }
]
layout = {
  'title': 'Top 20 Universities statistics - # of Students(size) and International score(color) in 2016',
  'xaxis' : dict(title = "University World Rank"),
  'yaxis' : dict(title = "Teaching scores")
};
fig = go.Figure(data = data, layout = layout)
iplot(fig)

In [ ]:
Question 14.3: Come up with your own question and make a bubble chart